# Generated by Django 4.2.16 on 2026-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_program_pdf_event_registration_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recording_url',
            field=models.URLField(blank=True, help_text='URL YouTube, Zoom ou autre plateforme vidéo', null=True, verbose_name='Lien enregistrement (YouTube/Zoom)'),
        ),
    ]
