# Generated by Django 4.2.16 on 2026-08-20 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre autorisé',
                'verbose_name_plural': 'Membres autorisés',
                'ordering': ['name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='LabEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projet', models.CharField(blank=True, max_length=150, verbose_name='Projet')),
                ('type_event', models.CharField(choices=[('Formation', 'Formation'), ('Séminaire', 'Séminaire'), ('Réunion', 'Réunion'), ('Conférence', 'Conférence'), ('Atelier', 'Atelier'), ('Table ronde', 'Table ronde'), ('Tournage', 'Tournage'), ('Recrutement', 'Recrutement'), ('Autre', 'Autre')], default='Réunion', max_length=40, verbose_name='Type')),
                ('titre', models.CharField(max_length=300, verbose_name="Titre de l'événement")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('heure', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('responsable', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('invites', models.CharField(blank=True, max_length=300, verbose_name='Invités')),
                ('besoins_com', models.TextField(blank=True, verbose_name='Besoins de communication')),
                ('besoins_prod', models.TextField(blank=True, verbose_name='Besoins de production')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('fait', 'Fait'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='a_venir', max_length=20, verbose_name='Statut')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Budget validé')),
                ('created_by', models.EmailField(blank=True, max_length=254, verbose_name='Ajouté par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement (planning)',
                'verbose_name_plural': 'Événements (planning)',
                'ordering': ['date_debut', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
