# Generated by Django 4.2.16 on 2026-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_add_member_globalafrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedmember',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin (peut générer des liens de connexion)'),
        ),
        migrations.AddField(
            model_name='logintoken',
            name='ttl_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
